{
 "title": "Windows Exporter Dashboard",
 "description": "According to Task Manager",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Stations",
    "query": {
     "query": "label_values(exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exported_instance) (\n  rate(windows_cpu_time_total{mode=~\"user|system|interrupt|dpc\", exported_instance=\"$instance\"}[30s])\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (process) (\n  rate(windows_process_cpu_time_total{process!~\"Idle|System|Registry\",exported_instance=\"$instance\"}[1m])\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "targets": [
    {
     "expr": "(\n  windows_memory_physical_total_bytes{exported_instance=\"$instance\"}\n  -\n  windows_memory_physical_free_bytes{exported_instance=\"$instance\"}\n) / (1024*1024*1024)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "topk(5,\n  sum by (process) (\n    windows_process_working_set_bytes{exported_instance=\"$instance\"}\n  ) / (1024 * 1024)\n)\nunless ignoring (process) (\n  windows_process_start_time_seconds{exported_instance=\"$instance\"} == 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (windows_memory_physical_total_bytes{exported_instance=~\"$instance\"} - windows_memory_available_bytes{exported_instance=~\"$instance\"})\n  /\n  windows_memory_physical_total_bytes{exported_instance=~\"$instance\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Space", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Empty Space in Disks (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{\n  exported_instance=\"$instance\",\n  volume=~\"C:|D:\"\n} / (1024 * 1024 * 1024)\n",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Usage Percentage of Disks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  windows_logical_disk_free_bytes{\n    exported_instance=\"$instance\",\n    volume=~\"C:|D:\"\n  }\n  /\n  windows_logical_disk_size_bytes{\n    exported_instance=\"$instance\",\n    volume=~\"C:|D:\"\n  }\n) * 100\n",
     "legendFormat": "{{volume}}"
    }
   ]
  }
 ]
}