#receivers:
#  prometheus:
#    config:
#      scrape_configs:
#        - job_name: 'remote-node-exporters'
#          scrape_interval: 10s
#          static_configs:
#            - targets: ["192.168.1.41:9100"]  # Client 1 IP
#              labels:
#                instance: "Emir Mac"
#            - targets: ["192.168.1.95:9100"]  # Client 2 IP
#              labels:
#                instance: "Windows"
#
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'windows-clients'
          scrape_interval: 10s
          static_configs:
            - targets: ["192.168.93.69:9182"]
              labels:
                instance: "windows-exporter"
            - targets: ["172.31.99.166:9182"]
              labels:
                instance: "test-PC"

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
