receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"  

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
